/** Sample "Commerce Platform" workspace used on first run (and by "Reset to sample"). */
import type { Context, DomainNodeInput, GlossaryTerm, Relationship } from "./model";

type SeedContext = Omit<Context, "x" | "y">;

export const SAMPLE_PROJECT_NAME = "Commerce Platform";

export const defaultContexts: SeedContext[] = [
  {
    id: "context-orders",
    name: "Orders",
    purpose: "Capture purchase intent and coordinate fulfillment.",
    color: "#e87554",
    nodeCount: 0,
    relationshipCount: 0,
  },
  {
    id: "context-inventory",
    name: "Inventory",
    purpose: "Keep stock truthful across warehouses and channels.",
    color: "#55b7a8",
    nodeCount: 0,
    relationshipCount: 0,
  },
  {
    id: "context-payments",
    name: "Payments",
    purpose: "Authorize, capture, and reconcile money movement.",
    color: "#9184d8",
    nodeCount: 0,
    relationshipCount: 0,
  },
];

export const defaultNodes: Array<DomainNodeInput & { id: string }> = [
  {
    id: "node-order",
    contextId: "context-orders",
    kind: "aggregate",
    name: "Order",
    description: "The transactional boundary for a customer purchase.",
    status: "validated",
    x: 24,
    y: 28,
    tags: ["core", "transactional"],
    methods: ["place()", "addLineItem()", "cancel()"],
    invariants: [
      "Order must have at least one line item before place()",
      "Cancelled orders cannot be modified",
      "Total equals sum of line amounts",
    ],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-order-root",
    contextId: "context-orders",
    kind: "aggregate-root",
    name: "OrderRoot",
    description: "Guards order invariants and publishes lifecycle events.",
    status: "validated",
    x: 34,
    y: 45,
    tags: ["root"],
    methods: ["assertInvariants()", "publishEvents()"],
    invariants: ["Only OrderRoot may publish OrderPlaced"],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-place-order",
    contextId: "context-orders",
    kind: "command",
    name: "PlaceOrder",
    description: "Customer intent to create a new order.",
    status: "validated",
    x: 16,
    y: 18,
    tags: ["event-storming"],
    methods: [],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-order-placed",
    contextId: "context-orders",
    kind: "domain-event",
    name: "OrderPlaced",
    description: "A durable fact that downstream contexts can react to.",
    status: "validated",
    x: 50,
    y: 20,
    tags: ["event-storming", "integration"],
    methods: [],
    invariants: [],
    eventVersion: "1.2.0",
    eventPayloadSchema: JSON.stringify(
      {
        type: "object",
        required: ["orderId", "customerId", "placedAt"],
        properties: {
          orderId: { type: "string", format: "uuid" },
          customerId: { type: "string", format: "uuid" },
          placedAt: { type: "string", format: "date-time" },
          lineCount: { type: "integer", minimum: 1 },
        },
      },
      null,
      2,
    ),
    eventCompatibility: "backward",
  },
  {
    id: "node-order-repo",
    contextId: "context-orders",
    kind: "repository",
    name: "OrderRepository",
    description: "Persistence boundary for the Order aggregate.",
    status: "needs-review",
    x: 20,
    y: 66,
    tags: ["port"],
    methods: ["findById()", "save()"],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-fulfillment",
    contextId: "context-inventory",
    kind: "service",
    name: "FulfillmentService",
    description: "Reserves inventory after an order is placed.",
    status: "draft",
    x: 68,
    y: 38,
    tags: ["application"],
    methods: ["reserveStock()", "handleOrderPlaced()"],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-stock",
    contextId: "context-inventory",
    kind: "aggregate-root",
    name: "StockItem",
    description: "The consistency boundary for available inventory.",
    status: "validated",
    x: 82,
    y: 54,
    tags: ["root", "inventory"],
    methods: ["reserve()", "release()", "availableQuantity()"],
    invariants: ["available + reserved == onHand", "reserve cannot exceed available"],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-payment",
    contextId: "context-payments",
    kind: "service",
    name: "PaymentGateway",
    description: "Resource exposed to authorize payment providers.",
    status: "validated",
    x: 62,
    y: 70,
    tags: ["resource", "external"],
    methods: ["authorize()", "capture()", "refund()"],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-payment-api",
    contextId: "context-payments",
    kind: "resource",
    name: "Payments API",
    description: "Domain API for authorization and capture.",
    status: "needs-review",
    x: 78,
    y: 78,
    tags: ["api"],
    methods: ["authorizePayment()", "capturePayment()"],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-payments-acl",
    contextId: "context-orders",
    kind: "anti-corruption-layer",
    name: "PaymentsACL",
    description: "Translates Orders language to Payments gateway DTOs.",
    status: "validated",
    x: 48,
    y: 62,
    tags: ["integration", "acl"],
    methods: ["toAuthorizeRequest()", "fromCaptureResponse()"],
    invariants: ["Never leak Payment provider IDs into Order aggregate"],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
  },
  {
    id: "node-fulfillment-saga",
    contextId: "context-orders",
    kind: "saga",
    name: "FulfillmentSaga",
    description: "Orchestration saga: central coordinator for OrderPlaced then reserve, charge, ship; compensates on failure.",
    status: "draft",
    x: 58,
    y: 36,
    tags: ["process", "orchestration"],
    methods: ["onOrderPlaced()", "onStockReserved()", "onPaymentAuthorized()", "compensate()"],
    invariants: ["Compensation runs if payment fails after stock reserved"],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
    sagaStyle: "orchestration",
    cqrsSide: "none",
  },
  {
    id: "node-place-order-cmd",
    contextId: "context-orders",
    kind: "command",
    name: "PlaceOrder",
    description: "Intent to create an order (CQRS write side).",
    status: "draft",
    x: 12,
    y: 12,
    tags: ["cqrs", "write"],
    methods: [],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
    sagaStyle: "none",
    cqrsSide: "command",
  },
  {
    id: "node-place-order-handler",
    contextId: "context-orders",
    kind: "command-handler",
    name: "PlaceOrderHandler",
    description: "CQRS command executor: applies PlaceOrder on Order aggregate and raises OrderPlaced.",
    status: "draft",
    x: 28,
    y: 12,
    tags: ["cqrs", "write"],
    methods: ["handle(PlaceOrder)"],
    invariants: ["Exactly one handler per command type"],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
    sagaStyle: "none",
    cqrsSide: "command",
  },
  {
    id: "node-order-list-rm",
    contextId: "context-orders",
    kind: "read-model",
    name: "OrderListView",
    description: "CQRS query projection of orders for listing UI.",
    status: "draft",
    x: 72,
    y: 12,
    tags: ["cqrs", "read"],
    methods: ["project(OrderPlaced)", "project(OrderCancelled)"],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
    sagaStyle: "none",
    cqrsSide: "query",
  },
  {
    id: "node-order-query-handler",
    contextId: "context-orders",
    kind: "query-handler",
    name: "GetOrderListHandler",
    description: "CQRS query side: reads OrderListView only (no domain writes).",
    status: "draft",
    x: 88,
    y: 12,
    tags: ["cqrs", "read"],
    methods: ["handle(GetOrderList)"],
    invariants: ["Must not mutate aggregates"],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
    sagaStyle: "none",
    cqrsSide: "query",
  },
  {
    id: "node-inventory-policy",
    contextId: "context-inventory",
    kind: "policy",
    name: "WhenOrderPlacedReserveStock",
    description: "Choreography: local policy reacts to OrderPlaced and issues ReserveStock (no central saga).",
    status: "draft",
    x: 20,
    y: 40,
    tags: ["choreography"],
    methods: [],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
    sagaStyle: "choreography",
    cqrsSide: "none",
  },
  {
    id: "node-reserve-stock-cmd",
    contextId: "context-inventory",
    kind: "command",
    name: "ReserveStock",
    description: "Intent to reserve inventory for an order line.",
    status: "draft",
    x: 40,
    y: 40,
    tags: ["cqrs", "write"],
    methods: [],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "",
    eventCompatibility: "backward",
    sagaStyle: "none",
    cqrsSide: "command",
  },
  {
    id: "node-stock-reserved-ev",
    contextId: "context-inventory",
    kind: "domain-event",
    name: "StockReserved",
    description: "Inventory fact used by choreography peers and optional orchestrator.",
    status: "draft",
    x: 60,
    y: 40,
    tags: ["event"],
    methods: [],
    invariants: [],
    eventVersion: "1.0.0",
    eventPayloadSchema: "{ orderId, sku, qty }",
    eventCompatibility: "backward",
    sagaStyle: "none",
    cqrsSide: "none",
  },
];

export const defaultRelationships: Relationship[] = [
  {
    id: "rel-place-order",
    sourceId: "node-place-order",
    targetId: "node-order",
    type: "uses",
    label: "creates",
    contextId: "context-orders",
  },
  {
    id: "rel-root-order",
    sourceId: "node-order",
    targetId: "node-order-root",
    type: "composition",
    label: "contains",
    contextId: "context-orders",
  },
  {
    id: "rel-order-event",
    sourceId: "node-order-root",
    targetId: "node-order-placed",
    type: "publishes",
    label: "publishes",
    contextId: "context-orders",
  },
  {
    id: "rel-fulfillment",
    sourceId: "node-fulfillment",
    targetId: "node-order-placed",
    type: "subscribes",
    label: "reacts to",
    contextId: "context-inventory",
  },
  {
    id: "rel-stock",
    sourceId: "node-fulfillment",
    targetId: "node-stock",
    type: "uses",
    label: "reserves",
    contextId: "context-inventory",
  },
  {
    id: "rel-payment",
    sourceId: "node-order-root",
    targetId: "node-payment",
    type: "invokes",
    label: "authorizes",
    contextId: "context-payments",
  },
  {
    id: "rel-payment-api",
    sourceId: "node-payment",
    targetId: "node-payment-api",
    type: "exposed-by",
    label: "exposed by",
    contextId: "context-payments",
  },
  {
    id: "rel-acl",
    sourceId: "node-order-root",
    targetId: "node-payments-acl",
    type: "uses",
    label: "protects boundary",
    contextId: "context-orders",
  },
  {
    id: "rel-acl-payment",
    sourceId: "node-payments-acl",
    targetId: "node-payment",
    type: "anti-corruption",
    label: "ACL",
    contextId: "context-orders",
  },
  {
    id: "rel-saga-event",
    sourceId: "node-fulfillment-saga",
    targetId: "node-order-placed",
    type: "subscribes",
    label: "orchestrates",
    contextId: "context-orders",
  },
  {
    id: "rel-ctx-orders-inventory",
    sourceId: "node-order-placed",
    targetId: "node-fulfillment",
    type: "customer-supplier",
    label: "Customer-Supplier",
    contextId: "context-orders",
  },
  {
    id: "rel-cmd-triggers-event",
    sourceId: "node-place-order-cmd",
    targetId: "node-order-placed",
    type: "triggers",
    label: "triggers",
    contextId: "context-orders",
  },
  {
    id: "rel-handler-handles-cmd",
    sourceId: "node-place-order-handler",
    targetId: "node-place-order-cmd",
    type: "handles",
    label: "handles",
    contextId: "context-orders",
  },
  {
    id: "rel-event-projects-rm",
    sourceId: "node-order-placed",
    targetId: "node-order-list-rm",
    type: "projects-to",
    label: "projects to",
    contextId: "context-orders",
  },
  {
    id: "rel-query-handler-rm",
    sourceId: "node-order-query-handler",
    targetId: "node-order-list-rm",
    type: "uses",
    label: "reads",
    contextId: "context-orders",
  },
  {
    id: "rel-saga-orchestrates",
    sourceId: "node-fulfillment-saga",
    targetId: "node-order-placed",
    type: "orchestrates",
    label: "orchestrates",
    contextId: "context-orders",
  },
  {
    id: "rel-policy-reacts",
    sourceId: "node-inventory-policy",
    targetId: "node-order-placed",
    type: "reacts-to",
    label: "reacts to",
    contextId: "context-inventory",
  },
  {
    id: "rel-policy-triggers-reserve",
    sourceId: "node-inventory-policy",
    targetId: "node-reserve-stock-cmd",
    type: "triggers",
    label: "issues",
    contextId: "context-inventory",
  },
  {
    id: "rel-reserve-triggers-event",
    sourceId: "node-reserve-stock-cmd",
    targetId: "node-stock-reserved-ev",
    type: "triggers",
    label: "triggers",
    contextId: "context-inventory",
  },
  {
    id: "rel-choreography-peer",
    sourceId: "node-inventory-policy",
    targetId: "node-stock-reserved-ev",
    type: "choreographs",
    label: "choreographs",
    contextId: "context-inventory",
  },
];

export const defaultGlossary: GlossaryTerm[] = [
  {
    id: "term-order",
    term: "Order",
    definition: "A customer commitment to purchase one or more line items under a single transactional boundary.",
    contextId: "context-orders",
    aliases: ["Purchase", "Sales order"],
    relatedNodeIds: ["node-order", "node-order-root"],
  },
  {
    id: "term-reserve",
    term: "Reserve",
    definition: "Temporarily hold inventory quantity so it cannot be sold twice before payment settles.",
    contextId: "context-inventory",
    aliases: ["Hold", "Allocation"],
    relatedNodeIds: ["node-stock"],
  },
  {
    id: "term-authorize",
    term: "Authorize",
    definition: "Request a payment provider to freeze funds without capturing them yet.",
    contextId: "context-payments",
    aliases: ["Auth"],
    relatedNodeIds: ["node-payment"],
  },
];
